version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: ht-db-service-${VERSION}
    restart: always
    ports:
      - 27018:27017
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - ht-go-net

  mongo-express:
    image: mongo-express
    container_name: ht-db-viewer-service-${VERSION}
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    networks:
      - ht-go-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ht-backend-service-${VERSION}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
    env_file: .env
    networks:
      - ht-go-net

volumes:
  mongodbdata:
    driver: local

networks:
  ht-go-net:
    name: ht-go-net
